-- =============================================
-- Chehar Temple - Blocked Email Domains Table
-- Stores disposable/temporary email domains
-- Admin can add/remove via API without code change
-- =============================================

CREATE TABLE IF NOT EXISTS blocked_email_domains (
    id BIGSERIAL PRIMARY KEY,
    domain VARCHAR(255) NOT NULL UNIQUE,
    reason VARCHAR(500) DEFAULT 'Disposable email service',
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_blocked_domains_domain ON blocked_email_domains(domain);

-- Seed with known disposable email domains
INSERT INTO blocked_email_domains (domain, reason, created_at) VALUES
('yopmail.com', 'Disposable email service', NOW()),
('yopmail.fr', 'Disposable email service', NOW()),
('yopmail.net', 'Disposable email service', NOW()),
('mailinator.com', 'Disposable email service', NOW()),
('mailinator2.com', 'Disposable email service', NOW()),
('mailinator.net', 'Disposable email service', NOW()),
('guerrillamail.com', 'Disposable email service', NOW()),
('guerrillamail.net', 'Disposable email service', NOW()),
('guerrillamail.org', 'Disposable email service', NOW()),
('guerrillamail.de', 'Disposable email service', NOW()),
('guerrillamailblock.com', 'Disposable email service', NOW()),
('guerrillamail.biz', 'Disposable email service', NOW()),
('guerrillamail.info', 'Disposable email service', NOW()),
('grr.la', 'Disposable email service', NOW()),
('sharklasers.com', 'Disposable email service', NOW()),
('tempmail.com', 'Disposable email service', NOW()),
('temp-mail.org', 'Disposable email service', NOW()),
('temp-mail.io', 'Disposable email service', NOW()),
('10minutemail.com', 'Disposable email service', NOW()),
('10minutemail.net', 'Disposable email service', NOW()),
('10minute.email', 'Disposable email service', NOW()),
('throwaway.email', 'Disposable email service', NOW()),
('throwaway.com', 'Disposable email service', NOW()),
('fakeinbox.com', 'Disposable email service', NOW()),
('fakeinbox.info', 'Disposable email service', NOW()),
('trashmail.com', 'Disposable email service', NOW()),
('trashmail.net', 'Disposable email service', NOW()),
('trashmail.me', 'Disposable email service', NOW()),
('trashmail.org', 'Disposable email service', NOW()),
('dispostable.com', 'Disposable email service', NOW()),
('maildrop.cc', 'Disposable email service', NOW()),
('getnada.com', 'Disposable email service', NOW()),
('tempail.com', 'Disposable email service', NOW()),
('mohmal.com', 'Disposable email service', NOW()),
('burnermail.io', 'Disposable email service', NOW()),
('mailnesia.com', 'Disposable email service', NOW()),
('mailcatch.com', 'Disposable email service', NOW()),
('tempr.email', 'Disposable email service', NOW()),
('discard.email', 'Disposable email service', NOW()),
('discardmail.com', 'Disposable email service', NOW()),
('discardmail.de', 'Disposable email service', NOW()),
('spamgourmet.com', 'Disposable email service', NOW()),
('mytemp.email', 'Disposable email service', NOW()),
('mt2015.com', 'Disposable email service', NOW()),
('thankyou2010.com', 'Disposable email service', NOW()),
('trash-mail.com', 'Disposable email service', NOW()),
('harakirimail.com', 'Disposable email service', NOW()),
('jetable.org', 'Disposable email service', NOW()),
('mailexpire.com', 'Disposable email service', NOW()),
('mailforspam.com', 'Disposable email service', NOW()),
('safetymail.info', 'Disposable email service', NOW()),
('filzmail.com', 'Disposable email service', NOW()),
('mailmoat.com', 'Disposable email service', NOW()),
('mailnull.com', 'Disposable email service', NOW()),
('spamfree24.org', 'Disposable email service', NOW()),
('spamhole.com', 'Disposable email service', NOW()),
('trashymail.com', 'Disposable email service', NOW()),
('mailzilla.com', 'Disposable email service', NOW()),
('tempomail.fr', 'Disposable email service', NOW()),
('ephemail.net', 'Disposable email service', NOW()),
('getairmail.com', 'Disposable email service', NOW()),
('meltmail.com', 'Disposable email service', NOW()),
('spaml.de', 'Disposable email service', NOW()),
('uggsrock.com', 'Disposable email service', NOW()),
('mailmetrash.com', 'Disposable email service', NOW()),
('binkmail.com', 'Disposable email service', NOW()),
('spamavert.com', 'Disposable email service', NOW()),
('incognitomail.org', 'Disposable email service', NOW()),
('mailblocks.com', 'Disposable email service', NOW()),
('spamex.com', 'Disposable email service', NOW()),
('lhsdv.com', 'Disposable email service', NOW()),
('trbvm.com', 'Disposable email service', NOW()),
('cuvox.de', 'Disposable email service', NOW()),
('armyspy.com', 'Disposable email service', NOW()),
('dayrep.com', 'Disposable email service', NOW()),
('einrot.com', 'Disposable email service', NOW()),
('fleckens.hu', 'Disposable email service', NOW()),
('gustr.com', 'Disposable email service', NOW()),
('jourrapide.com', 'Disposable email service', NOW()),
('rhyta.com', 'Disposable email service', NOW()),
('superrito.com', 'Disposable email service', NOW()),
('teleworm.us', 'Disposable email service', NOW()),
('tmpmail.net', 'Disposable email service', NOW()),
('tmpmail.org', 'Disposable email service', NOW()),
('emailondeck.com', 'Disposable email service', NOW()),
('mintemail.com', 'Disposable email service', NOW()),
('mailhazard.com', 'Disposable email service', NOW()),
('mailhazard.us', 'Disposable email service', NOW()),
('spamcowboy.com', 'Disposable email service', NOW()),
('spamcowboy.net', 'Disposable email service', NOW()),
('spamcowboy.org', 'Disposable email service', NOW()),
('mailscrap.com', 'Disposable email service', NOW()),
('mail-temporaire.fr', 'Disposable email service', NOW()),
('spam4.me', 'Disposable email service', NOW()),
('emkei.cz', 'Disposable email service', NOW()),
('anonymbox.com', 'Disposable email service', NOW()),
('courrieltemporaire.com', 'Disposable email service', NOW()),
('tempmailaddress.com', 'Disposable email service', NOW()),
('emailfake.com', 'Disposable email service', NOW()),
('crazymailing.com', 'Disposable email service', NOW()),
('tempmailo.com', 'Disposable email service', NOW()),
('emailtemporario.com.br', 'Disposable email service', NOW())
ON CONFLICT (domain) DO NOTHING;
